Feature/lga 3059 ci cd pipeline
ministryofjustice/laa-civil-case-api pull request #5
Opened 2024-06-19 07:55 UTC by TawneeOwl

2024-06-19 11:03 UTC, digitalali-moj requested changes
This looks great Kyle. Some things to chat through when you get a sec, but really awesome stuff!

2024-06-19 11:03 UTC, digitalali-moj commented on helm_deploy/laa-civil-case-api/templates/tests/test-connection.yaml
> +apiVersion: v1
Is this being used anywhere? If not can we remove it?

2024-06-19 11:03 UTC, digitalali-moj commented on requirements/generated/requirements.txt
> +# This file is autogenerated by pip-compile with Python 3.7
Are we using Python 3.7 or 3.9 like the docker image?

2024-06-19 12:07 UTC, digitalali-moj submitted a review, later dismissed
Fantastic work!

2024-06-24 09:44 UTC, Pheonnexx approved these changes
LGTM - at least you caught those copy paste mistakes!

2024-06-24 09:49 UTC, merged